apiVersion: v2
version: 2.2.0
name: openebs
appVersion: 2.1.0
description: Containerized Storage for Containers
icon: https://raw.githubusercontent.com/cncf/artwork/master/projects/openebs/icon/color/openebs-icon-color.png
home: http://www.openebs.io/
keywords:
  - cloud-native-storage
  - block-storage
  - iSCSI
  - storage
sources:
  - https://github.com/openebs/openebs
dependencies:
  - name: openebs-ndm
    version: 0.8.0
    repository: "https://sonasingh46.github.io/ndm-charts/"
maintainers:
  - name: kmova
    email: kiran.mova@openebs.io
  - name: prateekpandey14
    email: prateek.pandey@openebs.io
